# Generated by Django 5.1.6 on 2025-02-23 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacts",
            options={"verbose_name": "Контакты", "verbose_name_plural": "Контакты"},
        ),
        migrations.RemoveField(
            model_name="networknode",
            name="Contacts",
        ),
        migrations.AddField(
            model_name="networknode",
            name="contacts",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="network.contacts",
                verbose_name="Контакты",
            ),
        ),
    ]
