# Generated by Django 5.1.6 on 2025-02-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_alter_contacts_options_remove_networknode_contacts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="networknode",
            name="contacts",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="network.contacts",
                verbose_name="Контакты",
            ),
        ),
    ]
